baseURL = "https://canche.com"
title = "Home"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 10

[params]
  customheadingFontFamily = "Heebo-ExtraLight"
