baseURL = "https://canche.com"
title = "Richard Stone"

[markup]
  defaultMarkdownHandler = 'blackFriday'
  [markup.blackFriday]
    hrefTargetBlank = true

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 10

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "mailto:richardstonereyes@gmail.com"
    weight = 20

[params]
  customheadingFontFamily = "Heebo-ExtraLight"